---
# Define the valid endpoints here. Usually, we will have one for production
# and one for staging purposes.
#
# In case of Letsencrypt, you will need a different account key for each of
# them.
#
endpoints:
  production:
    url: https://acme-v02.api.letsencrypt.org/directory
    private_key: /etc/acme-deploy/accounts/production/private-key.pem
    email_addr: certs@example.com
  staging:
    url: https://acme-staging-v02.api.letsencrypt.org/directory
    private_key: /etc/acme-deploy/accounts/staging/private-key.pem
    email_addr: certs@example.com

# Define all the certificates you want here. Each certificate needs at least
# a subject (CN), a private key and a path where to store it.
#
# For key and path values, you can use the variable {{endpoint}} which will
# get replaced by the actual endpoint name.
#
certificates:
  ssl.example.com:
    subject: ssl.example.com
    san:
      - ssl2.example.com
      - ssl3.example.com
    key: /etc/acme-deploy/{{endpoint}}/keys/ssl.example.com.key
    path: /etc/acme-deploy/{{endpoint}}/certs/ssl.example.com.pem
    renew_days: 30

  secure.example.com:
    subject: secure.example.com
    key: /etc/acme-deploy/{{endpoint}}/keys/secure.example.com.key
    path: /etc/acme-deploy/{{endpoint}}/certs/secure.example.com.pem
    renew_days: 30

# Define our web servers the challenge responses will be created at. For each
# server, at least hostname and acme_path has to be specified. acme_path is
# the path on the remote system where the file containing the challenge 
# response will be put. Make sure that the specified user on the destination
# system has write permission to the directory specified by acme_path. Do
# yourself a favor and do not use the root user for connecting to the remote
# system.
#
connectors:
  frontend_web_1:
    hostname: www1.example.com
    username: acme
    ssh_port: 22
    acme_path: /var/www/acme
    type: ssh_http_file
  frontend_web_2:
    hostname: www2.example.com
    username: acme
    ssh_port: 22
    acme_path: /var/www/acme
    type: ssh_http_file

# Set some sane defaults for your environment here.
defaults:
  endpoint: staging
  renew_days: 30
  type: ssh_http_file
